/** All prices in Rwandan Francs (RWF). */
export const productsSeed = [
  {
    name: "Emerald Rain Pendant",
    price: 165000,
    currency: "RWF",
    category: "Necklaces",
    badge: "BESTSELLER",
    sku: "BP-PEN-001",
    material: "14k Gold & Emerald",
    active: true,
    image: "/assets/products/jw1.png",
    description: "Radiant emerald centerpiece on a delicate 14k gold chain.",
    stock: 15,
  },
  {
    name: "Golden Flora Bracelet",
    price: 152000,
    currency: "RWF",
    category: "Bracelets",
    badge: "NEW",
    sku: "BP-BRA-002",
    material: "Sterling Silver",
    active: true,
    image: "/assets/products/jw 2.png",
    description: "Floral-inspired links with warm gold finish.",
    stock: 8,
  },
  {
    name: "Bold Emerald Bracelet",
    price: 190000,
    currency: "RWF",
    category: "Bracelets",
    badge: "BESTSELLER",
    sku: "BP-BRA-003",
    material: "14k Gold",
    active: true,
    image: "/assets/products/jw 3.png",
    description: "Statement emerald stones set in polished gold.",
    stock: 3,
  },
  {
    name: "Emerald Drop Earrings",
    price: 139000,
    currency: "RWF",
    category: "Earrings",
    badge: "NEW",
    sku: "BP-EAR-004",
    material: "Sterling Silver",
    active: true,
    image: "/assets/products/jw5.png",
    description: "Elegant drop silhouette with vivid green stones.",
    stock: 15,
  },
  {
    name: "Verdant Glow Ring",
    price: 178000,
    currency: "RWF",
    category: "Rings",
    badge: "LIMITED",
    sku: "BP-RIN-005",
    material: "14k Gold & Emerald",
    active: true,
    image: "/assets/products/jw6.png",
    description: "Solitaire emerald in a classic gold band.",
    stock: 0,
  },
  {
    name: "Luxe Chain Necklace",
    price: 127000,
    currency: "RWF",
    category: "Necklaces",
    badge: "NEW",
    sku: "BP-PEN-006",
    material: "Sterling Silver",
    active: false,
    image: "/assets/products/jw7.png",
    description: "Minimal chain designed for everyday elegance.",
    stock: 20,
  },
];
